name: Exercise tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    name: Go ${{ matrix.go-version }} - ${{ matrix.os }}/${{ matrix.test-arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.20.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        test-arch: [amd64]
        race: ["-race"]

        include:
          - go-version: 1.20.x
            test-arch: "386"
            os: ubuntu-latest
            race: ""
          - go-version: 1.20.x
            test-arch: "386"
            os: windows-latest
            race: ""

    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753
        with:
          go-version: ${{ matrix.go-version }}

      - name: Lint and Test exercises
        shell: bash
        env:
          GOARCH: ${{ matrix.test-arch }}
        run: |
          ./bin/fetch-golangci-lint
          ./bin/run-tests
